[build]
  base = "frontend/"
  publish = "build/"

[template.environment]
  NODE_ENV = "production"  

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  query = {path = ":path"}
