previewsEnabled: true
services:
  - type: web
    name: ToolJet
    plan: free
    env: docker
    repo: https://github.com/ToolJet/ToolJet.git
    dockerfilePath: ./docker/production.Dockerfile
    dockerCommand: npm run db:seed:prod && npm run start:prod
    dockerContext: ./
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-preview
          property: connectionString
      - key: TOOLJET_HOST
        fromService:
          type: web
          name: ToolJet
          envVarKey: RENDER_EXTERNAL_URL
      - key: TOOLJET_SERVER_URL
        fromService:
          type: web
          name: ToolJet
          envVarKey: RENDER_EXTERNAL_URL
      - fromGroup: tooljet-preview-env
databases:
  - name: postgres-preview
    plan: free
    databaseName: tooljet_preview
    postgresMajorVersion: 13
