version: "3"

services:
  tooljet:
    tty: true
    stdin_open: true
    container_name: Tooljet-app
    image: tooljet/tooljet-ce:latest
    restart: always
    env_file: .env
    ports:
      - 80:80
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    depends_on:
      - redis
    command: npm run start:prod
  # Uncomment if ENABLE_TOOLJET_DB=true
  postgrest:
    image: postgrest/postgrest:v10.1.1.20221215
    restart: always
    env_file: .env
    environment:
      - PGRST_SERVER_PORT=80

  redis:
    container_name: ${REDIS_HOST}
    image: redis:6.2
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data
    env_file:
      - .env
    environment:
      - MASTER=${REDIS_HOST}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
