apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooljet-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      component: tooljet
  template:
    metadata:
      labels:
        component: tooljet
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: container
          image: tooljet/tooljet-ce:latest
          imagePullPolicy: Always
          args: ["npm", "run", "start:prod"]
          resources:
            limits:
              memory: "1000Mi"
              cpu: "500m"
            requests:
              memory: "1000Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              port: 3000
              path: /api/health
            successThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          env:
            - name: PG_HOST
              value: ""
            - name: PG_USER
              value: "postgres"
            - name: PG_PASS
              value: ""
            - name: PG_DB
              value: ""
            - name: LOCKBOX_MASTER_KEY
              value: ""
            - name: SECRET_KEY_BASE
              value: ""
            - name: TOOLJET_HOST
              value: "https://tooljet.your-domain.com"
            - name: DEPLOYMENT_PLATFORM            
              value: "k8s:gke"
            - name: REDIS_HOST
              value: tooljet-redis-service.default.svc.cluster.local
            - name: REDIS_USER
              value: default
            - name: REDIS_PASSWORD
              value:              
            # Set the env values below for Tooljet Database
            # - name: ENABLE_TOOLJET_DB
            #   value: "true"
            # - name: TOOLJET_DB
            #   value: "tooljet_db"
            # - name: TOOLJET_DB_USER
            #   value: "replace_with_tooljet_db_user"
            # - name: TOOLJET_DB_HOST
            #   value: "replace_with_tooljet_db_host"
            # - name: TOOLJET_DB_PASS
            #   value: "replace_with_tooljet_db_pass"
            # - name: PGRST_HOST
            #   value: "replace_with_postgrest_host"
            # - name: PGRST_JWT_SECRET
            #   value: "replace_pgrst_jwt_secret_here"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tooljet-redis-statefulset
spec:
  selector:
    matchLabels:
      role: tooljet-redis
  serviceName: tooljet-redis-service
  replicas: 1
  template:
    metadata:
      labels:
        role: tooljet-redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis:6.0
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: tooljet-redis-persistent-storage
            mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: tooljet-redis-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: tooljet-redis-service
  labels:
    name: tooljet-redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    role: tooljet-redis            
