name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.17.3
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.3
    - run: npm i -g npm@7.20.0
    - run: npm ci
    - run: npm run build

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.17.3
      uses: actions/setup-node@v2
      with:
        node-version: 14.17.3
    - run: npm i -g npm@7.20.0
    - run: npm --prefix frontend ci && npm --prefix server ci
    - name: Lint
      run: npm --prefix server run lint && npm --prefix frontend run lint
