name: Cypress e2e-test

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          browser: chrome
