name: Cypress e2e-test

on:
  push:
    branches: [develop]

  workflow_dispatch:
    inputs:
      URL:
        description: Enter the Render PR URL

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for app to start
        run: |
          while true; do
          curl --silent --fail ${{ github.event.inputs.URL }} && break
          sleep 1
          done

      - name: Start web app
        run: |
          npm run cy:open

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Cypress tests
        run: |
          npx cypress run run --config baseUrl=${{ github.event.inputs.URL }}
