name: Cypress E2E testing

on:
  workflow_dispatch:
    inputs:
      URL:
        description: Enter the Render PR URL

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 16.13.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2

      - name: Cypress integration test
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./cypress-tests
          start: npm run cy:run -- --config baseUrl=${{ github.event.inputs.URL }}
          config: "baseUrl=${{ github.event.inputs.URL }}"
          config-file: cypress.config.js
