name: Heroku Review Application
on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, closed]
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, closed]

jobs:
  heroku-review-application:
    name: Heroku Review Application
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy-heroku')
    steps:
      - name: Heroku Review Application
        uses: mheap/github-action-pr-heroku-review-app@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_PIPELINE_ID: ${{ secrets.HEROKU_PIPELINE_ID }}
          LOCKBOX_MASTER_KEY: ${{secrets.LOCKBOX_MASTER_KEY}}
          NODE_ENV: "production"
          NODE_OPTIONS: "--max-old-space-size=4096"
          SECRET_KEY_BASE: ${{secrets.SECRET_KEY_BASE}}
          TOOLJET_HOST: "https://tooljet-pr-${{github.event.number}}.herokuapp.com"
          TOOLJET_SERVER_URL: "https://tooljet-pr-${{github.event.number}}.herokuapp.com"
