name: Deploy to netfliy 

on:
  
  push:
    branches: [develop]
  pull_request: 
    branches: [develop]
    
  workflow_dispatch:
  
jobs:

  build:
  
    runs-on: ubuntu-latest
  
    steps:
 
    - uses: actions/checkout@v2
  
    - name: Deploy site
      run: curl -X POST -d {} ${{ secrets.NETLIFY_HOOK }}
