name: Label for stale render deploys
on:
  push
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: akshaysasidrn/stale-label-fetch@v1.1
      id: stale-label
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        stale-label: 'active-review-app'
        stale-time: '1'
        type: 'pull_request'
    - name: Get stale numbers
      run: echo "matched PR numbers ${{ steps.stale-label.outputs.stale-numbers }}"
    - name: Add suspend label
      uses: actions/github-script@v6.3.3
      env:
        STALE_NUMBERS: ${{ steps.stale-label.outputs.stale-numbers }}
      with:
        script: |
          if (!process.env.STALE_NUMBERS) return

          const prNumbers = process.env.STALE_NUMBERS.split(",")
          for (const prNumber of prNumbers) {
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['suspend-review-app']
            })
          }
