name: Try-Tooljet Docker Image

on:
  release: 
    types: [published]
    branches:
      - main

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set DOCKER_CLI_EXPERIMENTAL
        run: echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Check if Docker image is present
        id: check-image-presence
        run: |
          response=$(curl -s "https://hub.docker.com/v2/repositories/tooljet/tooljet-ce/tags/${{ github.event.release.tag_name }}")
          if [[ $? -ne 0 ]]; then
            echo "Failed to fetch JSON response. Stopping workflow execution."
            exit 1
          fi

          if [[ $response == *"tag '${{ github.event.release.tag_name }}' not found"* ]]; then
            echo "Docker image tag '${{ github.event.release.tag_name }}' not present."
            exit 1
          else
            echo "Docker image tag '${{ github.event.release.tag_name }}' is present."
          fi

      - name: Build and Push Docker image
        run: |
          docker buildx build --platform=linux/amd64 -f docker/try-tooljet.Dockerfile . -t tooljet/try:latest
          docker push tooljet/try:latest
